# For more information: https://laravel.com/docs/sail
version: "3"
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.1/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
        expose:
            - 9009
        environment:
            WWWUSER: "${WWWUSER}"
            # LARAVEL_SAIL: 1
            # XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            # XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
            - ./docker/xdebug.ini:/etc/php/8.1/cli/conf.d/20-xdebug.ini
        networks:
            - sail
        depends_on:
            - database

    database:
        image: postgres:13
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - sail
        volumes:
            - "sailpgsql:/var/lib/postgresql/data"

    adminer:
        image: "adminer"
        networks:
            - sail
        ports:
            - 8080:8080
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
