name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: set fly command line tool
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        run: flyctl deploy -c fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
